include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

queues {
  "outbox-events.fifo" {
    fifo = true
    contentBasedDeduplication = false
    defaultVisibilityTimeout = 30 seconds
  }
}
